// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR8WokXlB7Lxr9TiC6fruOMDbKJMAF2Fs',
    appId: '1:128926670957:web:f2a268a268781cdaae1f64',
    messagingSenderId: '128926670957',
    projectId: 'diary-contact',
    authDomain: 'diary-contact.firebaseapp.com',
    databaseURL: 'https://diary-contact-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diary-contact.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt7pOhY_AXsg9mhdWglUBuRCW1rmRVayc',
    appId: '1:128926670957:android:566b7260cc959c2cae1f64',
    messagingSenderId: '128926670957',
    projectId: 'diary-contact',
    databaseURL: 'https://diary-contact-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diary-contact.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkizH6f-Q9lxS2j94w-d7__ICdCxx8bCY',
    appId: '1:128926670957:ios:589a739a77dcc86dae1f64',
    messagingSenderId: '128926670957',
    projectId: 'diary-contact',
    databaseURL: 'https://diary-contact-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diary-contact.appspot.com',
    androidClientId: '128926670957-7nim300bc9os75ptpk2je59pu2hie96l.apps.googleusercontent.com',
    iosClientId: '128926670957-f9fros9mp3u3atnvif1laa6oq4bphkd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.diary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkizH6f-Q9lxS2j94w-d7__ICdCxx8bCY',
    appId: '1:128926670957:ios:589a739a77dcc86dae1f64',
    messagingSenderId: '128926670957',
    projectId: 'diary-contact',
    databaseURL: 'https://diary-contact-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diary-contact.appspot.com',
    androidClientId: '128926670957-7nim300bc9os75ptpk2je59pu2hie96l.apps.googleusercontent.com',
    iosClientId: '128926670957-f9fros9mp3u3atnvif1laa6oq4bphkd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.diary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR8WokXlB7Lxr9TiC6fruOMDbKJMAF2Fs',
    appId: '1:128926670957:web:d5bbd8f99f20f301ae1f64',
    messagingSenderId: '128926670957',
    projectId: 'diary-contact',
    authDomain: 'diary-contact.firebaseapp.com',
    databaseURL: 'https://diary-contact-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diary-contact.appspot.com',
  );

}